/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

import org.junit.Test;

import com.capgi.StackAndQueue;

import static org.junit.Assert.*;

public class StackAndQueueTest {
    @Test public void testSomeLibraryMethod() {
        StackAndQueue classUnderTest = new StackAndQueue();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
