/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class StackAndQueueTest {
	@Test
	public void stackPushOperationTest() {
		StackAndQueue stack = new StackAndQueue();
		Node<Integer> firstNode = new Node<Integer>(70);
		Node<Integer> secondNode = new Node<Integer>(30);
		Node<Integer> thirdNode = new Node<Integer>(56);
		stack.push(firstNode);
		stack.push(secondNode);
		stack.push(thirdNode);
		stack.printStack();

		boolean result = stack.peek().equals(thirdNode);
		assertTrue(result);

	}

}
