/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

public class Stack {
	LinkedList linkedList;

	public Stack() {
		this.linkedList = new LinkedList();
	}

	public void push(INode newNode) {
		linkedList.add(newNode);
	}

	public void pop() {
		linkedList.pop();
	}

	public INode peek() {
		return linkedList.getHead();
	}

	public int size() {
		return linkedList.sizeOfList();
	}

	public boolean isEmpty() {
		if (size() > 0) {
			return true;
		} else
			return false;

	}

	public void printStack() {
		linkedList.printLinkedList();
	}
}
