/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

public class StackAndQueue {
	public void push(INode newNode) {
		LinkedList linkedList = new LinkedList<>();
		linkedList.add(newNode);
	}
}
